title: Food Integrity Directory
description: >-
  A static directory for integrity-based food systems, starting in Aotearoa New Zealand.
baseurl: ""   # e.g. "/homegrown-directory" if using project pages
url: ""       # e.g. "https://stonetoskycreations.github.io"

collections:
  farms:
    output: true
    permalink: /farms/:country/:slug/
  markets:
    output: true
    permalink: /markets/:country/:slug/
  stores:
    output: true
    permalink: /stores/:country/:slug/
  restaurants:
    output: true
    permalink: /restaurants/:country/:slug/
  distributors:
    output: true
    permalink: /distributors/:country/:slug/

markdown: kramdown
plugins: []
